apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-dir-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 50Gi # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Or Delete, Recycle based on your preference
  hostPath:
    path: /mnt/data/jupyterhub # Ensure this path exists on all nodes
