#!/bin/bash
# storageClass.yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath # trùng với PV
provisioner: kubernetes.io/no-provisioner # nôm na là ko dùng cloud service
volumeBindingMode: WaitForFirstConsumer
